### ISSUE TITLE
시연을 위한 기능 요청 - Side Navigation Bar 수정

### ISSUE THREAD

**Issue by Yejining** [AntAlbum/frontend#20]
## 기능 요청사항
기능 분류대로 side navigation bar가 만들어지면 좋겠습니다.

## 요청 세부사항
travel, 계정 설정, attraction 등으로 나뉘면 좋겠습니다.

## 레퍼런스
- 현재
  ![image](https://github.com/AntAlbum/frontend/assets/33994508/818b6e10-4e8e-4fb5-9373-86bcc45c559a)

**Comment by rnrlgus** [comment]
<img width="265" alt="image" src="https://github.com/AntAlbum/frontend/assets/76944225/066df185-8754-4624-b85b-08795407f4cc">
완료했습니다.
