### ISSUE TITLE
시연을 위한 기능 요청 - 홈 화면 수정 요청

### ISSUE THREAD

**Issue by Yejining** [AntAlbum/frontend#21]
## 기능 요청사항
홈 화면을 풍성하게 채우는 것을 요청합니다.

## 요청 세부사항
- Coursel
- 사용자 프로필
- 알람 버튼 삭제

## 레퍼런스
- Mockup
  ![그림1](https://github.com/AntAlbum/frontend/assets/33994508/c4cc7fa9-7b2a-4067-b431-d5caffc556a2)

**Comment by rnrlgus** [comment]
완료했습니다.
![image](https://github.com/AntAlbum/frontend/assets/76944225/e9b9f949-b623-47d2-9f43-ec60154d9af7)

**Comment by rnrlgus** [comment]
<img width="1440" alt="image" src="https://github.com/AntAlbum/frontend/assets/76944225/3bdf99ef-c911-4475-a934-0c76cccd09cd">
귀여운 펭귄입니다

**Comment by rnrlgus** [comment]
![image](https://github.com/AntAlbum/frontend/assets/76944225/e3595bf0-4719-4d84-a078-9ce07aaa58a2)
최종본입니다.
